[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
env_logger = "0.11.6"
zip = "2.2.2"
notify = "7.0.0"
ftp = "3.0.1"
chrono = "0.4.39"
sha2 = "0.11.0-pre.4"
hex = "0.4.3"
walkdir = "2.5.0"
